### ISSUE TITLE
Add scroll to top button on blog post pages

### ISSUE THREAD

**Issue by Garrett1Tolbert** [blaccsmith/website#10]
## Is your feature request related to a problem? If so, please describe.
No problem, just something cool to go on the page

## Describe the solution you'd like.
An scroll to top arrow that appears when you scroll down past a certain point. When you hover, it starts glowing in a cool way ✨💫

## Describe alternatives you've considered
Haven't considered any alternatives. This is an Easter egg that'd be cool on the page.

## Additional context
N/A

**Comment by DarrylBrooks97** [comment]
Completed and Closing
