### ISSUE TITLE
Helpful APIs section

### ISSUE THREAD

**Issue by Garrett1Tolbert** [blaccsmith/website#30]
## Is your feature request related to a problem? Please describe.
There's tons of different APIs to do a bunch of different things. It's overwhelming the amount of choices available so I'm not sure what's best to use for a particular project or task. 

## Describe the solution you'd like.
I'd like to see a curated list of APIs that the community has had positive experience with. 

## Describe alternatives you've considered
Going down rabbit holes of poorly documented APIs

## Additional context
It'd be cool if the APIs could be categorized by language / framework they are used with and also a thread of comments so others can talk about their experience with that API

**Comment by DarrylBrooks97** [comment]
Can expand it for highly useful repos and other helpful tech on Github. Looking into this
