### ISSUE TITLE
Fetch Github Info

### ISSUE THREAD

**Issue by DarrylBrooks97** [blaccsmith/website#34]
### Is your feature request related to a problem? Please describe

No problem

### Describe the solution you'd like

When a Github repo url is submitted we should be able to fetch information about the repo

### Describe alternatives you've considered

No alternatives

**Comment by DarrylBrooks97** [comment]
- [ ] Analysis on setting up Graphql
- [ ] Use Graphql for fetching Github info on submit
- [ ] Storage info in Supabase

**Comment by DarrylBrooks97** [comment]
Thinking the most useful info to display from the [api](https://docs.github.com/en/rest/reference/repos) maybe:
- Top 3 topics
- stargazers_count

**Comment by blaccsmith** [comment]
Completed in #36 and closing

**Comment by blaccsmith** [comment]
Completed in #36 and closing
