### ISSUE TITLE
BLACC Blog

### ISSUE THREAD

**Issue by DarrylBrooks97** [blaccsmith/website#5]
## Is your feature request related to a problem? Please describe.
People come to BLACC looking for individuals that they can relate to. The best way to do this is to crowd source experience, tips & tricks from members within the community allowing potential new members to know this is the place for them.

## Describe the solution you'd like
Reach out to members within the community and ask if they would be willing to write about anything that could add value to the community. 
 
## Describe alternatives you've considered
Crowdsourcing Youtube channel

## Additional context
Exploring the creation of MDX files for members of the community to write their content

**Comment by Garrett1Tolbert** [comment]
@DarrylBrooks97 What type of labels should we consider for a blog post?

**Comment by blaccsmith** [comment]
A sandbox needs to be created for authors to view their article while they're editing it

**Comment by cawrites** [comment]
Is there someone or a group leading the review effort to make sure the content has a consistent look and feel? It would be good to have some type of contributer guide, but also clearly state what is acceptable content for the space.

**Comment by cawrites** [comment]
@blaccsmith if you use a tool like VSCode you can see your content in preview mode.

**Comment by DarrylBrooks97** [comment]
Hey @cawrites great question. @Garrett1Tolbert and I will be the reviewers of the content to make sure they are consistent and coherent. 

We're currently building a sandbox that renders the blog content consistently #19

**Comment by DarrylBrooks97** [comment]
Completed and Closing
